Feature/us17/creation page contact
Martin-Hayot/Projet-Integration-2023 pull request #22
Opened 2023-11-13 02:20 UTC by Samaze123

# US 17

## Ajout de la page contact dans le backend

### Ajout des fonctionnalité indispensable coté backend

- app.js : Ajout de la route contact dans le routeur
- tickets.js : Ajout du modèle de ticket de la base de données
- user.js : Ajout de l'attribut ability dans le User ce qui permet <d'être> admin des tickets et d'avoir les droits de :
  - visionner les tickets ouverts.
  - supprimer les tickets.
- auth.js : Ajout d'une réponse lors du login qui sera stockée dans le localstorage du client pour éviter de devoir faire plusieurs requêtes similaires.
- contact.js : Creation de la route :
  - Ajouter, supprimer et recevoir les tickets.
  - Ajout d'un get avec un Id particulier pour avoir plus de controle si on le souhaite.

#### Tests Backend

- Suite a des problèmes avec jest, je suis parti sur les tests de Postman (L'équipe va peut-être partir sur Postman aussi pour avoir du CI/CD facilement mais a voir)
  - Le lien vers la team Sonde et mes tests dans le dossier contact : <https://app.getpostman.com/join-team?invite_code=477582489e38f4fd84cf3c0b9be48ff5&target_code=e68351644d42b560e6cf34f2a3328911>

## Ajout de la page Contact dans le front

### Cette page permet aux utilisateur qui le souhaite de faire parvenir chez les développeur des idées ou autres

- app.tsx : Ajout de la page contact et ticket viewer dans le routeur du front
- ContactUS.tsx : Création de la page contact

## Ajout de la page tickets Viewer

### Cette page sert a visionner tous les tickets ouverts par les utilisateurs

#### Pour l'instant n'a pas de pagination ce qui pourrait créer des problemes dans le futur

- tickets.tsx : Ajout du composant Ticket pour une réutilisation ultérieure plus facile
- TicketsViewer.tsx : Création de la page admin de lecture des tickets.

## Autre

### Ajouts divers utile au reste du site

- Ajout de la réponse du login recue du back dans le local storage
- Dashboard.tsx : Ajout d'un lien vers la page contact dans le dashboard car pas de navbar utilisable
- components/index.ts : Ajout des nouveaux composants dans la liste de composants
- Navbar.tsx : Ajout de lien vers les différente page et mise a jour de la navbar en fonction de l'état de l'utilisateur.
- main.tsx : Ajout d'un userProvider et userContext pour avoir accès a plusieurs données dans le front sans faire de requêtes.
- userContext.tsx : Ajout du context dans un composant réutilisable
- userProvider.tsx : Ajout du rovider dans un composant réutilisable mis sur la racinde du website
- About.tsx : Ajout de la navbar dans la page About
- pages/index.ts : Ajout des pages dans la liste d'import
- DOSSIER /types : Ajout de fichiers contenant les différents types utilisés dans certains modules .TSX.
- Changements mineurs dans différents fichier qui importent leur types depuis le dossier créé.

2023-11-14 12:03 UTC, Julien00859 commented
Bel effort pour le changelog, vous me présentez ça jeudi je serai content. Pour encore améliorer le style, on comprend en lisant l'ensemble des points qu'il s'agit d'une page contact avec un système (léger) de ticketing, je pense que ce serait intéressant d'avoir une introduction (avant l'énumération des changements) qui vienne expliquer sur 1/2 paragraphe la fonctionnalité en générale, le "pourquoi" c'est utile pour le client.

Je ne vois qu'un test unitaire de 30 lignes pour 600 lignes de code, je trouve ça plutôt léger. C'est bien de vérifier que la route retourne bien une réponse 200, c'est mieux de vérifier que les infos ont été correctement enregistrées en base. Pensez peut-être aussi à rajouter un test pour l'interface, par exemple qui viendrait vérifier qu'on ne peut pas soumettre un formulaire si tous les champs obligatoires ne sont pas remplis.

2023-11-15 09:52 UTC, Samaze123 commented
> Bel effort pour le changelog, vous me présentez ça jeudi je serai content. Pour encore améliorer le style, on comprend en lisant l'ensemble des points qu'il s'agit d'une page contact avec un système (léger) de ticketing, je pense que ce serait intéressant d'avoir une introduction (avant l'énumération des changements) qui vienne expliquer sur 1/2 paragraphe la fonctionnalité en générale, le "pourquoi" c'est utile pour le client.
> 
> Je ne vois qu'un test unitaire de 30 lignes pour 600 lignes de code, je trouve ça plutôt léger. C'est bien de vérifier que la route retourne bien une réponse 200, c'est mieux de vérifier que les infos ont été correctement enregistrées en base. Pensez peut-être aussi à rajouter un test pour l'interface, par exemple qui viendrait vérifier qu'on ne peut pas soumettre un formulaire si tous les champs obligatoires ne sont pas remplis.

- Ajout d'une explication fait.
- Ajout de tests back et front fait.

Changement de deux trois fonctionnalités expliquées dans le message de commit.

2023-11-16 15:03 UTC, Samaze123 commented
Suite a un échange avec le groupe, j'ai changé la route en mettant un middleware et j'ai retiré ability du body pour cette requete, c'est le serveur qui va faire la requete pour voir si l'email recu est celle d'un admin ou pas

2023-11-16 15:59 UTC, Samaze123 commented
Retrait des attribut style et remplacement par du tailwind

2023-11-18 13:03 UTC, JarodEphec commented on g-sonde/src/pages/TicketsViewer.tsx
> +			return;
Ce code ne fonctionne pas, quand je ne suis pas autorisé, un toast apparaît avec un page vide sauf la navbar, mais je ne suis pas déconnecté et je ne suis pas amené sur la page de login.

2023-11-18 13:07 UTC, JarodEphec commented on g-sonde/src/components/UserProvider.tsx
> +	);
Nous avions parlé de l'utilisation du local storage et du problème de sécurité qu'il peut amener dans ce cas. Tu as bien fait les changements, pas de soucis, mais je vois toujours du local storage dans ton code, peux-tu m'expliquer la raison ?

2023-11-18 13:07 UTC, JarodEphec requested changes
Salut Samuel, bon travail pour cette pull request !

J'ai quelques remarques à faire.

1. Lorsque j'envoie un ticket et que tout à fonctionner, je n'ai pas de retour au niveau de la page, il faudrait ajouter un retour visuel pour montrer à l'utilisateur que son ticket a bien été envoyé. Je vois dans le code qu'il y a un toast pour une erreur, mais pas pour une réussite, le toast serait un bon retour visuel, mais je trouve qu'une page montrant a l'utilisateur que son ticket a bien été envoyé avec son id de ticket, serait vraiment le summum du retour visuel utilisateur.

2. Quand je suis arrivé sur la page pour voir les tickets, il y avait juste les champs que l'utilisateur avait rentrés (nom, description) et l'id du ticket, mais pas d'information pour contacter l'utilisateur. Lors de la première itération de cette pour request, tu avais fait de sorte que le client mail s'ouvre automatiquement, avec des informations préremplies pour l'utilisateur. Je trouve que ici, ça serait intéressent de remettre cette fonctionnalité, mais cette fois si pour l'admin.
3. Je vois que la seule option disponible pour les tickets est de les supprimer, je pense qu'il serait plus intéressent de les archivés pour avoir un historique des tickets envoyé et comme ça, d'avoir une trace des différents problèmes que les utilisateurs ont lors de l'utilisation de notre solution.
4. Pour l'ouverture de tickets, ça serait bien d'avoir des catégories pour pouvoir trier les tickets et en plus, en mettant des catégories spécifiques, ça rendra ton US encore plus spécifique.
5. Je ne vois pas de test pour la page `/admin/tickets`.
6. Il y a dû refactoring de code dans ta pull request, ça passe ici car c'est du code que tu utilises dans ton US, mais fait attention dans le futur.

2023-11-18 13:21 UTC, bahuwart reviewed
J'ai pas grand chose à dire de plus que Jarod.
Beau travail UwU

2023-11-18 13:21 UTC, bahuwart commented on backend/routes/contact.js
> +});
Salut sam, tu dis dans la pull request que tu as finalement abandonné le champs "ability" mais là je vois que il y a une route ability. J'imagine qu'elle va être enlevée aussi ?
Sinon super boulot : )

2023-11-18 13:27 UTC, JarodEphec commented on backend/routes/contact.js
> +});
Non, justement, si tu regardes le commit 1f150587e92511a3f2ba9a47a168f82f7676dba7, tu peux voir qu'il a ajouté la route `/ability` justement pour vérifier que l'utilisateur ait bien le droit de voir les tickets.

2023-11-18 15:10 UTC, Samaze123 commented on g-sonde/src/components/UserProvider.tsx
> +	);
J'ai laissé le local storage seulement pour plus de facilité du coté du frontend. Ce qui se trouve dedans sert juste au front qu'est-ce qu'il faut affiché ou pas, ils ne sont plus utilisés dans les requêtes. Est-ce que ca te va ou tu préfère que je retire quand même ?

2023-11-18 16:59 UTC, Samaze123 commented on backend/routes/contact.js
> +});
On disait que le localStorage n'était pas sécurisé et c'est vrai donc ca il fallait le supprimé mais je garde la partie ability pour savoir si un user est admin ou pas. Juste, la confirmation ne viendra pas du localStorage mais bien du serveur et de ses vérifications

2023-11-18 17:46 UTC, JarodEphec commented on g-sonde/src/components/UserProvider.tsx
> +	);
Enfaite, si une requête est faite au back end pour faire ce que ce code faisait, je ne vois pas très bien la raison de le garder, ces variables en local storage peuvent-elles être remplacées par des variables ?

2023-11-19 02:59 UTC, Samaze123 commented
J'ai fini normalement d'ajouter ce qu'on a conseillé !

2023-11-19 13:27 UTC, Samaze123 commented on g-sonde/src/components/UserProvider.tsx
> +	);
oui oui en vrai je vais retiré le local storage.

2023-11-19 13:37 UTC, Samaze123 commented on g-sonde/src/components/UserProvider.tsx
> +	);
En fait, je stocke ces données dans le localStorage juste pour pouvoir ne pas demandé au back a chaque changement de page. C'est plus performant au pris de sécurité, et encore le seul truc qui pourrait pose problème si quelqu'un arrivait a changer son localStorage, c'est qu'il verrait des boutons qu'il n'est pas senser voir. Mais au moment ou il cliquerait dessus il serait deconnecté et renvoyer au login.

2023-11-19 20:10 UTC, bahuwart commented on backend/routes/contact.js
> +});
ah ok compris lol

2023-11-19 20:38 UTC, Samaze123 commented on g-sonde/src/pages/TicketsViewer.tsx
> +			return;
Code réparé ! Merci du retour !!

2023-11-20 20:56 UTC, JarodEphec requested changes
![Capture d'écran 2023-11-20 214709](https://github.com/Martin-Hayot/Projet-Integration-2023/assets/92374656/57bbb933-1610-4b39-b5aa-cac67f3a75f0)

Ici, on peut voir que ma catégorie avec un nom trop long fait buguer le bouton radio, je sais que tu utilises le composant de ionic, sais-tu faire quelque chose pour ça ?

Sinon, ton US est vraiment impressionnant pour le travail fourni, la beauté de tes pages et les fonctionnalités avancées qu'elles apportent.

2023-11-20 20:56 UTC, JarodEphec commented on g-sonde/src/pages/CategoryManager.tsx
> +		}
J'ai remarqué que ici, tu n'autorises pas les espaces, ce qui est dérangeant pour écrire une catégorie de problème comme "Problème de conexion avec la sonde".

2023-11-21 10:33 UTC, Samaze123 commented on g-sonde/src/pages/CategoryManager.tsx
> +		}
Je viens de commit les changements:
- Ajout d'un style qui met a la ligne les mots ou phrases trop longue. (pour le radio bouton)
- Ajout des espaces dans les regex.

2023-11-22 13:41 UTC, JarodEphec approved these changes
Parfait !

2023-11-22 14:03 UTC, merged