Feature/us16/profil
Martin-Hayot/Projet-Integration-2023 pull request #29
Opened 2023-11-23 02:43 UTC by Martin-Hayot

2023-11-24 10:35 UTC, Julien00859 commented
You're asking me a lot of reviews and frankly I just cannot keep pace, can you instead select which PR you actually want my review and ping me at most once a week? I'm also interested to see how you review each other. I would suggest you to ping me at the very end, when you're confident the PR is ready to be merge. Unsubscribing for now, ping me at the end :p

2023-11-25 16:04 UTC, JarodEphec requested changes
Salut Martin, très bon travail. Si j'avais su que l'on pouvait enregistrer des images comme ça en DB, ça m'aurait sauvé de quelques soucis en DEV3, enfin, j'ai juste quelques remarques à faire.

- Le changement de password ne fonctionne pas, ce qui est bizarre, car la vérification entre le nouveau et l'ancien password lui fonctionne.  
- C'est un peu bizarre que quand on va sur la page, on me demande mon email, je trouve que cette information devrait être rentrée par défaut et que dans le modal, il ne soit pas possible de la changer, parce que là, on demande les anciennes infos, je ne sais pas si tu me comprends ? Une fois dans le modal, ça serait peut-être mieux de mettre une indication comme quoi, on demande les informations de connexion avant changement.
- Je peux me rendre sur la page sans être connecté, j'imagine que pour ce problème, tu attends d'avoir les `UserContextes` de Samuel ?
- Un petit test de render en front ne ferait pas de mal.

2023-11-25 16:50 UTC, JarodEphec commented on g-sonde/src/pages/User/Profile.tsx
> +            )
Nouveau mdp envoyé en clair ?

2023-11-25 17:12 UTC, JarodEphec commented on g-sonde/src/pages/User/Profile.tsx
> +                                        ></IonInput>
[Ionic Warning]: ion-input now requires providing a label with either the "label" property or the "aria-label" attribute. To migrate, remove any usage of "ion-label" and pass the label text to either the "label" property or the "aria-label" attribute.

Example: <ion-input label="Email"></ion-input>
Example with aria-label: <ion-input aria-label="Email"></ion-input>

For inputs that do not render the label immediately next to the input, developers may continue to use "ion-label" but must manually associate the label with the input by using "aria-labelledby".

Developers can use the "legacy" property to continue using the legacy form markup. This property will be removed in an upcoming major release of Ionic where this form control will use the modern form markup.

2023-11-25 17:51 UTC, JarodEphec commented on backend/routes/user.js
> +            hashedPassword,
Je pense avoir trouvé le fix pour le changement de password : 
```
password: hashedPassword,
```

2023-11-27 10:28 UTC, Martin-Hayot commented on g-sonde/src/pages/User/Profile.tsx
> +            )
Oui c'est comme pour la création de compte, on est obligé de faire comme ça

2023-11-27 10:34 UTC, Martin-Hayot commented on backend/routes/user.js
> +            hashedPassword,
je comprends pas ce que tu veux dire par ça. Pourrais tu me donner plus de contexte ?

2023-11-27 10:48 UTC, Martin-Hayot commented
> Salut Martin, très bon travail. Si j'avais su que l'on pouvait enregistrer des images comme ça en DB, ça m'aurait sauvé de quelques soucis en DEV3, enfin, j'ai juste quelques remarques à faire.
> 
> * Le changement de password ne fonctionne pas, ce qui est bizarre, car la vérification entre le nouveau et l'ancien password lui fonctionne.
> * C'est un peu bizarre que quand on va sur la page, on me demande mon email, je trouve que cette information devrait être rentrée par défaut et que dans le modal, il ne soit pas possible de la changer, parce que là, on demande les anciennes infos, je ne sais pas si tu me comprends ? Une fois dans le modal, ça serait peut-être mieux de mettre une indication comme quoi, on demande les informations de connexion avant changement.
> * Je peux me rendre sur la page sans être connecté, j'imagine que pour ce problème, tu attends d'avoir les `UserContextes` de Samuel ?
> * Un petit test de render en front ne ferait pas de mal.

Pour le password je vais voir pourquoi il ne se modifie pas. Le formulaire est vide de base parce que toute les informations doivent être modifiable même l'email si jamais il veut changer l'endroit où arrive les notifications. Je vais rajouter un test e2e et modifier un peu la page pour un meilleur UX

2023-11-27 11:20 UTC, JarodEphec commented on backend/routes/user.js
> +            hashedPassword,
Ce qui fait que le password ne se change pas, avec ce que j'ai fait comme changement ici, il se change bien chez moi.

2023-11-27 11:21 UTC, JarodEphec commented
> > Salut Martin, très bon travail. Si j'avais su que l'on pouvait enregistrer des images comme ça en DB, ça m'aurait sauvé de quelques soucis en DEV3, enfin, j'ai juste quelques remarques à faire.
> > 
> > * Le changement de password ne fonctionne pas, ce qui est bizarre, car la vérification entre le nouveau et l'ancien password lui fonctionne.
> > * C'est un peu bizarre que quand on va sur la page, on me demande mon email, je trouve que cette information devrait être rentrée par défaut et que dans le modal, il ne soit pas possible de la changer, parce que là, on demande les anciennes infos, je ne sais pas si tu me comprends ? Une fois dans le modal, ça serait peut-être mieux de mettre une indication comme quoi, on demande les informations de connexion avant changement.
> > * Je peux me rendre sur la page sans être connecté, j'imagine que pour ce problème, tu attends d'avoir les `UserContextes` de Samuel ?
> > * Un petit test de render en front ne ferait pas de mal.
> 
> Pour le password je vais voir pourquoi il ne se modifie pas. Le formulaire est vide de base parce que toute les informations doivent être modifiable même l'email si jamais il veut changer l'endroit où arrive les notifications. Je vais rajouter un test e2e et modifier un peu la page pour un meilleur UX

Oui mais je trouve que tout ce qui est information comme le nom, prénom et adresse email devrait être prérempli.

2023-11-27 16:24 UTC, Martin-Hayot commented on backend/routes/user.js
> +            hashedPassword,
oui mais je ne comprends pas ou tu rajoute la ligne en question.

```js
const hashedPassword = await bcrypt.hash(password, 10);
const updateUser = await User.findByIdAndUpdate(userId, {
            firstname,
            lastname,
            email,
            password: hashedPassword,
        });
```

c'est ça qui marche chez toi ?

2023-12-06 17:49 UTC, JarodEphec approved these changes
Parfait, toutes mes remarques ont été prises en compte, good job !

2023-12-06 17:49 UTC, merged