Feature/us12/graphique
Martin-Hayot/Projet-Integration-2023 pull request #31
Opened 2023-11-25 12:08 UTC by JarodEphec

2023-11-25 21:10 UTC, Samaze123 requested changes
## Page Chart

Belle page pour montrer comment un graphique fonctionne.

Petits problèmes :

- Pas de navbar sur la page

## Composant Graphique

Le composant est bien fait mais voici des changment a faire :

- Quand je redimensionne la fenetre, le graphique dépasse et est presque coupé de moitié.
- Ne pas être obligé d'indiquer des titres pour le composants (les rendres optionels).

## Divers

Tu m'as dit en appel que le fichier *aquarium.tsx* doit être supprimé, ne l'oublie pas.

***Sinon dans l'ensemble c'est une belle fonctionnalité !***

2023-11-27 23:17 UTC, JarodEphec commented
> ## Page Chart
> 
> Belle page pour montrer comment un graphique fonctionne.
> 
> Petits problèmes :
> 
>     * Pas de navbar sur la page
> 
> 
> ## Composant Graphique
> 
> Le composant est bien fait mais voici des changment a faire :
> 
>     * Quand je redimensionne la fenetre, le graphique dépasse et est presque coupé de moitié.
> 
>     * Ne pas être obligé d'indiquer des titres pour le composants (les rendres optionels).
> 
> 
> ## Divers
> 
> Tu m'as dit en appel que le fichier _aquarium.tsx_ doit être supprimé, ne l'oublie pas.
> 
> _**Sinon dans l'ensemble c'est une belle fonctionnalité !**_

Salut Samuel, merci pour la review, j'ai fait tous les changements que tu m'as demandés.

Pour ce qui est des arguments de titres, j'ai fait le test et si tu ne mets rien, rien n'est affiché là où il y aurait les titres habituellement, tout fonctionne normalement.

2023-11-29 20:37 UTC, Samaze123 commented
Je viens de voir et ***package-lock.json*** est commit, je ne sais pas si c'est volontaire ou pas.

J'ai essayé tes changements et tout me semble correct pour moi ! 

Très chouettes graphiques.

2023-11-29 20:41 UTC, Samaze123 approved these changes

2023-12-01 15:03 UTC, merged