Chore/tt/dashboard
Martin-Hayot/Projet-Integration-2023 pull request #42
Opened 2023-12-06 19:22 UTC by bahuwart

Cette Pull Request consiste en la finalisation du dashboard en y incorporant les deniers éléments manquant comme des liens dans le menu déroulant permettant ainsi d'accéder directement aux pages de l'utilisateur sans devoir passer par l'url, ainsi que d'autres corrections de problèmes mineurs concernant le frontend. 

Cela comprend : 

- le lien faire la page d'accueil
- le lien vers la page contact
- le lien vers les tickets
- le lien vers les graphiques
- le lien vers le profile (pas encore totalement fini)

D'autres ajouts ont été fait comme l'ajout d'un lien direct entre les aquariums dans le dashboard et leur visualisation directement dans la page Charts qui contient les graphiques des différents aquariums de l'utilisateur.
En effet, lorsque l'on clique sur le bouton "voir les graphiques" dans le dashboard, l'aquarium en question est directement sélectionné.

Quand au frontend, les problèmes d'affichage notamment des boutons du dashboard ont été corrigés.

2023-12-06 22:22 UTC, Martin-Hayot commented
Voila les commentaires que j'ai à faire : 
- Tu utilise un veille version de app.js, tu pourrais juste prendre la nouvelle pour remplacer l'ancienne, ça ne posera pas de soucis.
- Notification.js, ce fichier viens de Serge, il faut donc : ou que ce code soit commit de la pr de Serge ou que tu supprime le fichier.
- Tu utilise les fichier data.js et diagnostic.js dans le backend, ces fichier n'existe plus car leurs contenue a été placer dans aquarium.js pour avoir un arborésence plus restfull.
- Tu as modifier l'indentation de Charts.js, ce qui rend l'indentation moins lisible, je te conseil d'activer l'indentation automatique dans VSCode avec Prettier.
- La page dashboard contient des éléments ancien que tu aurais du enlever car c'est le but de cet TT comme le bouton get Data qui renvoie Hello from server side ou dans le menu : this is the menu content
- Pour le menu : 
  - le texte Menu est pas bien centré sur la navbar
  -  les icones et le texte ne sont pas centré et pas parrallèle
  - il n'y a aucune réactivité quand je passe sur les liens. on ne dirait d'ailleurs pas que ce sont des liens. 
  - les icones ne sont pas clickables et ne devraient pas être aussi gros par rapport au texte. Je les mettrais personnellement avant le texte pour une meilleur UX.
  - Le menu n'est pas intégré sur toute les pages demandant une connexion ce qui donne l'impression qu'on change de site et ce qui rends l'expérience bizarre

Il y a plein de console.log et de message d'erreur dans le backend donc regarde aussi par là.
Il y a encore des conflits avec Develop et l'historique est à refaire quand tu auras fini de tout corriger.

2023-12-06 22:24 UTC, Martin-Hayot requested changes
J'ai fait un commentaire au dessus reprenant pour l'instant tout les changements à appliquer avant de merge

2023-12-12 13:38 UTC, Martin-Hayot requested changes
Les changements ne sont pas tous appliquer comme dis dans ton message de commit. En vue de ton dernier commit j'ai encore review mais la prochaine fois redemande une review comme ça je suis pingé sur la PR et  je dois pas moi même vérifier si des changements ont été fait. Merci

2023-12-13 17:58 UTC, bahuwart commented
Salut Martin merci pour ta review,
j'ai corrigé les problèmes que tu as soulevé,
par contre certains n'en sont pas, par exemple le fichier Notification.js est indispensable pour mon US et le fichier de Serge ou le mien sont les mêmes vu que j'ai été le prendre chez lui donc ça ne devrait pas poser soucis lors du rebase.

2023-12-19 15:01 UTC, Martin-Hayot approved these changes
Tout les changements demandé sont pris en compte et ajouté. Merci et bon travail !

2023-12-19 15:01 UTC, merged